default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("PUMA_THREADS_MAX") { 5 } %>
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  username: <%= ENV.fetch('DATABASE_USERNAME', 'root') %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  reconnect: <%= !!ENV.fetch('DATABASE_RECONNECT', false) %>
  reaping_frequency: <%= ENV.fetch("DATABASE_REAPING_FREQUENCY") { 60 } %>

development:
  <<: *default
  database: <%= ENV.fetch('DATABASE_DEVELOPMENT_NAME', 'kami_development') %>

test:
  <<: *default
  database: kami_test

#
production:
  <<: *default
  database: api_production
  username: api
  password: <%= ENV["API_DATABASE_PASSWORD"] %>
